export const START_LOADER = 'START_LOADER';
export const STOP_LOADER = 'STOP_LOADER';

export const REQUEST_GENRE = 'REQUEST_GENRE';
export const REQUEST_GENRE_SUCCESS = 'REQUEST_GENRE_SUCCESS';
export const REQUEST_GENRE_FAIL = 'REQUEST_GENRE_FAIL';
export const REQUEST_GENRE_COMPLETED = 'REQUEST_GENRE_COMPLETED';

export const REQUEST_POPULAR_MOVIES = 'REQUEST_POPULAR_MOVIES';
export const REQUEST_POPULAR_MOVIES_SUCCESS = 'REQUEST_POPULAR_MOVIES_SUCCESS';
export const REQUEST_POPULAR_MOVIES_FAIL = 'REQUEST_POPULAR_MOVIES_FAIL';
export const REQUEST_POPULAR_MOVIES_COMPLETED = 'REQUEST_POPULAR_MOVIES_COMPLETED';

export const REQUEST_MOVIE_DETAILS = 'REQUEST_MOVIE_DETAILS';
export const REQUEST_MOVIE_DETAILS_SUCCESS = 'REQUEST_MOVIE_DETAILS_SUCCESS';
export const REQUEST_MOVIE_DETAILS_FAIL = 'REQUEST_MOVIE_DETAILS_FAIL';
export const REQUEST_MOVIE_DETAILS_COMPLETED = 'REQUEST_MOVIE_DETAILS_COMPLETED';

export const REQUEST_MOVIE_RECOMMENDATION = 'REQUEST_MOVIE_RECOMMENDATION';
export const REQUEST_MOVIE_RECOMMENDATION_SUCCESS = 'REQUEST_MOVIE_RECOMMENDATION_SUCCESS';
export const REQUEST_MOVIE_RECOMMENDATION_FAIL = 'REQUEST_MOVIE_RECOMMENDATION_FAIL';
export const REQUEST_MOVIE_RECOMMENDATION_COMPLTED = 'REQUEST_MOVIE_RECOMMENDATION_COMPLTED';

export const REQUEST_LIST_MOVIE_FAVOURITES = 'REQUEST_LIST_MOVIE_FAVOURITES';
export const REQUEST_LIST_MOVIE_FAVOURITES_SUCCESS = 'REQUEST_LIST_MOVIE_FAVOURITES_SUCCESS';
export const REQUEST_LIST_MOVIE_FAVOURITES_COMPLETED = 'REQUEST_LIST_MOVIE_FAVOURITES_COMPLETED';

export const REQUEST_ADD_MOVIE_FAVOURITES = 'REQUEST_ADD_MOVIE_FAVOURITES';
export const REQUEST_ADD_MOVIE_FAVOURITES_SUCCESS = 'REQUEST_ADD_MOVIE_FAVOURITES_SUCCESS';
export const REQUEST_ADD_MOVIE_FAVOURITES_COMPLETED = 'REQUEST_ADD_MOVIE_FAVOURITES_COMPLETED';

export const REQUEST_REMOVE_MOVIE_FAVOURITES = 'REQUEST_ADD_MOVIE_FAVOURITES';
export const REQUEST_REMOVE_MOVIE_FAVOURITES_SUCCESS = 'REQUEST_REMOVE_MOVIE_FAVOURITES_SUCCESS';
export const REQUEST_REMOVE_MOVIE_FAVOURITES_COMPLTED = 'REQUEST_REMOVE_MOVIE_FAVOURITES_COMPLTED';
